// Mock products for demo purposes
const mockProducts = [
  {
    _id: '1',
    name: 'Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation.',
    price: 29.99,
    image: '/product-images/wireless-headphones.svg',
    category: 'Electronics',
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Cotton T-Shirt',
    description: 'Comfortable cotton t-shirt in various colors.',
    price: 49.99,
    image: '/product-images/cotton-tshirt.svg',
    category: 'Fashion',
    countInStock: 5,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Smartphone Case',
    description: 'Protective case for your smartphone.',
    price: 19.99,
    image: '/product-images/smartphone-case.svg',
    category: 'Electronics',
    countInStock: 15,
    rating: 4.2,
    numReviews: 20,
  },
  {
    _id: '4',
    name: 'Running Shoes',
    description: 'Lightweight running shoes for all terrains.',
    price: 79.99,
    image: '/product-images/running-shoes.svg',
    category: 'Fashion',
    countInStock: 8,
    rating: 4.7,
    numReviews: 15,
  },
  {
    _id: '5',
    name: 'Coffee Maker',
    description: 'Automatic coffee maker for perfect brew.',
    price: 89.99,
    image: '/product-images/coffee-maker.svg',
    category: 'Home',
    countInStock: 12,
    rating: 4.3,
    numReviews: 25,
  },
  {
    _id: '6',
    name: 'Skincare Set',
    description: 'Complete skincare set for healthy skin.',
    price: 39.99,
    image: '/product-images/skincare-set.svg',
    category: 'Beauty',
    countInStock: 20,
    rating: 4.6,
    numReviews: 30,
  },
  {
    _id: '7',
    name: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker with great sound.',
    price: 59.99,
    image: '/product-images/bluetooth-speaker.svg',
    category: 'Electronics',
    countInStock: 7,
    rating: 4.4,
    numReviews: 18,
  },
  {
    _id: '8',
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat for your practice.',
    price: 24.99,
    image: '/product-images/yoga-mat.svg',
    category: 'Home',
    countInStock: 25,
    rating: 4.1,
    numReviews: 22,
  },
];

module.exports = mockProducts;
